### ISSUE TITLE
Create Virtual-DOM nodes directly

### ISSUE THREAD

**Issue by wooorm** [yoshuawuyts/virtual-markdown#2]
It’s pretty easy to create a plugin for remark which directly creates virtual nodes. Taking [remark-html](https://github.com/wooorm/remark-html) as a base (which is already set up with a [`h()` function](https://github.com/wooorm/remark-html/blob/master/lib/h.js)). It’s been done in the past for [react](https://github.com/mapbox/mdast-react), and would be a good addition here too.

**Comment by yoshuawuyts** [comment]
yeah, this would be heaps better; if one is built PRs would definitely be welcome!

**Comment by wooorm** [comment]
OK I’ll see what I can whip-up in this festive week :)

**Comment by yoshuawuyts** [comment]
🙌🎉

**Comment by wooorm** [comment]
Created the plug-in: https://github.com/wooorm/remark-vdom

Do let me know of any suggestions!

**Comment by wooorm** [comment]
@yoshuawuyts Ping!

**Comment by yoshuawuyts** [comment]
haha, whoops. I've been super distracted the last few days :cat:. Thanks for making this hey!

**Comment by wooorm** [comment]
Fixed in [remark-vdom@1.0.1](https://github.com/wooorm/remark-vdom/commit/1d76efa9037b89dc1314ac7bb8746e909201e04c).

**Comment by wooorm** [comment]
Oh, whoops, wrong thread.
